//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEFTrial.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public int MarksID { get; set; }
        public int SubjectID { get; set; }
        public int StudentID { get; set; }
        public Nullable<int> Marks { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
