//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEFTrial.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SchoolSchemaEntities : DbContext
    {
        public SchoolSchemaEntities()
            : base("name=SchoolSchemaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClassRoom> ClassRooms { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<Mark> Marks { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<SubjectTeacherMap> SubjectTeacherMaps { get; set; }
    
        public virtual ObjectResult<SP_FetchStudentAggregatePercentage_Result> SP_FetchStudentAggregatePercentage()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_FetchStudentAggregatePercentage_Result>("SP_FetchStudentAggregatePercentage");
        }
    }
}
