//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEFTrial.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectTeacherMap
    {
        public int SubjectTeacherMapID { get; set; }
        public int SubjectID { get; set; }
        public int FacultyID { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
